inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - ./config.ru
    - ./Rakefile
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - script/rails

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
